### PR TITLE
Update Rakudo Star to 2022.04

### PR DESCRIPTION
**Pull request by MadcapJake**
Couldn't locate a fingerprint file so I rewrote the verification to use the sha256 checksum. I also split the run out into several of them and moved files to `ADD` and variables to `ENV` commands. This was to take better advantage of caching.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Not entirely sure what is going on here, despite it saying "All checks have passed"  the https://github.com/Raku/docker/pull/49/checks would seem to suggest otherwise.

**Comment by jonathanstowe** [comment]
> Not entirely sure what is going on here, despite it saying "All checks have passed" the https://github.com/Raku/docker/pull/49/checks would seem to suggest otherwise.

Oh it's showing correctly now.

**Comment by MadcapJake** [comment]
Looks like the GitHub action expects only one version.

**Comment by MadcapJake** [comment]
> > Not entirely sure what is going on here, despite it saying "All checks have passed" the https://github.com/Raku/docker/pull/49/checks would seem to suggest otherwise.
> 
> Oh it's showing correctly now.

@jonathanstowe should I:

- delete the old 2021.04 folder
- update action to take latest version, or
- update action matrix to also check at the version level?

I am not familiar with gha, am I able to enable on a fork for testing updates to it?

Thanks for your help!

**Comment by MadcapJake** [comment]
Closing as it appears there is movement towards generating the fingerprint and there's an existing PR that bumps the r* version.

**Pull request closed without merging**
