### PR TITLE
use -m option of useradd + add github action to test build

### PR DESCRIPTION
**Pull request by sthiriet**
fix my previous PR

### CODE REVIEW

**Review by JJ — COMMENTED** [review]
After accepting the previous one without actually testing it, I think I'm going to try and set up some way of testing PRs before I accept anything else. Please give us some time to set it up.

**Comment by sorairolake** [comment]
I think using `-m` option in `useradd` will create a home directory (as described in the [man page](https://manpages.debian.org/buster/passwd/useradd.8.en.html)).
In this case, I think that the code added in #41 (`mkdir` and `chown`) will be unneeded.

**Comment by sthiriet** [comment]
@sorairolake : 👍 
@JJ : I will try to use `-m` + init a github action that test the built image

**Comment by sthiriet** [comment]
In github workflow, in order to dynamically test all build without changing the action, I assume that the directory tree will remain  `<Version>/<BaseImages>/Dockerfile`

After the build step, i have added two tests, one with root and one with raku user that run a zef command that list installed module and a raku command that print raku version.
(the zef command failed with raku user before fixing the user directory creation). 
Probably there are more tests to add?

You can see the result here : https://github.com/sthiriet/docker/actions

**Comment by jmaslak** [comment]
@JJ - do you have a way of testing PRs yet?  This PR likely fixes a Dockerfile error that prevents building of the Buster image, so I'd like to see it submitted (but I don't know anything about github actions so I can't comment on that part of the PR).  I'd also like to submit a couple PRs to modernize the versions of Alpine and Rakudo-Star in Docker Hub.

**Comment by JJ** [comment]
I just missed this, sorry. Will do...

**Comment by jonathanstowe** [comment]
I'm a bit confused as to why the new github action in this PR didn't get triggered.   Maybe it's that it doesn't create the action for the first time until it's on the default branch.

**Comment by jonathanstowe** [comment]
Let's see how that goes.

**Comment by jonathanstowe** [comment]
Doesn't like the `--tag`

**Comment by jonathanstowe** [comment]
Just fixing that.

**Comment by jonathanstowe** [comment]
All good now.

**Pull request merged**
