### PR TITLE
Add Travis CI integration

### PR DESCRIPTION
**Pull request by wolverian**
This PR adds [Travis CI](https://travis-ci.org) integration to test that the image builds. The script in `.travis.yml` can be expanded to test the built image more thoroughly. 

You can see what the CI looks like at https://travis-ci.org/wolverian/docker.

The integration won't work until someone with admin rights to this repository gives Travis rights to read the repo, like documented at https://docs.travis-ci.com/user/getting-started.

### CODE REVIEW

**Comment by hoelzro** [comment]
Sounds good to me!  Thanks!

**Comment by hoelzro** [comment]
@wolverian Unfortunately I don't have admin access for the repo - I bet you could find someone on `#perl6` to enable it for you, though!

**Comment by moritz** [comment]
I've activated the perl6/docker repo on travis.

**Comment by hoelzro** [comment]
Thanks @moritz!

**Pull request merged**
