### PR TITLE
Bump to 2024.05

### PR DESCRIPTION
**Pull request by m-dango**

### CODE REVIEW

**Comment by ab5tract** [comment]
`404` errors seem to be causing issues with the CI pipelines. But I can't restart the jobs to check if it's a fluke.

**Comment by Altai-man** [comment]
I restarted the job and it seems the URL is unavailable.

**Comment by m-dango** [comment]
I saw the release announcement on GitHub and threw together a quick PR while I had the time, but seems I may have jumped the gun a bit 😅

**Comment by ab5tract** [comment]
I think the issue is that we still need a Rakudo Star release. But maybe that's a good cue to split this docker image into both a Rakudo and a Rakudo Star version?

**Pull request merged**
